### ISSUE TITLE
Google Calendar stopped working

### ISSUE THREAD

**Issue by oriadam** [trevorhreed/web-injection#1]
When WebInjector is enabled on Chrome browser, The Google Calendar is not working - I cannot add events.

**Comment by trevorhreed** [comment]
Apparently, the `console` object is undefined when in a tab running Google Calendar. Some of the default code in Web Injector uses `console.log`, which causes the error. This default code will be removed in a future version. Meanwhile, the workaround is simply to manually remove the offending code on the Web Injector options page.

**Comment by trevorhreed** [comment]
Fixed in v1.0.1
